export enum Province {
        'Blagoevgrad',
        'Burgas',
        'Varna',
        'Veliko Tarnovo',
        'Vidin',
        'Vratsa',
        'Gabrovo',
        'Dobrich',
        'Kardzhali',
        'Kyustendil',
        'Lovech',
        'Montana',
        'Pazardzhik',
        'Pernik',
        'Pleven',
        'Plovdiv',
        'Pazgrad',
        'Ruse',
        'Silistra',
        'Sliven',
        'Smolyan',
        'Sofia',
        'Stara Zagora',
        'Targovishte',
        'Haskovo',
        'Shumen',
        'Yambol'
}
